# ExpressJS settings
[express]
port = 64000
# Authorization keys used in "Authorization" header of the HTTP request
# "name" is just an identifier to recognize which key belongs to whom
authorization = [
  { name = "name_1", key = "key_1" },
  { name = "name_2", key = "key_2" },
  { name = "name_3", key = "key_3" },
]

# broker settings
[broker]
protocol = "amqp"
host = "localhost"
port = "5672"
username = ""
password = ""
heartbeat = 5
queue = ""